[package]
name = "rebalancing-tool"
version = "0.1.0"
authors = ["Chris Sketch <sketchc89@gmail.com>"]
edition = "2018"

[dependencies]
separator = "0.3.1"

#[dependencies.gtk]
#version = "0.5"
#features = ["v3_22"]
